title: Personal website
description: Personal website
url: "https://rosikand.github.io"
baseurl: ""
markdown: kramdown
kramdown:
  math_engine: mathjax

# Build settings
permalink: /posts/:title/
exclude:
  - charlieoneill11.github.io-main
  - vendor
  - README.md
  - Gemfile
  - Gemfile.lock
  - scripts
  - DEPLOYMENT.md
  - EDITING.md
  - LOCAL_DEV.md
  - WORKLOG.md
